import tkinter as ui
login=ui.Tk()
login.title("Login")
login.attributes("-fullscreen",True)
login.configure(bg="white")
header_main=ui.Label(login,text="WareHouse management system",bg="white")
header_main.config(font=("Times",30,"bold"))
header_main.place(relx=0.5,rely=0.1,anchor=ui.CENTER)
#header_main.pack()
username_lable=ui.Label(login,text="Enter username",bg="white")
username_lable.place(relx=0.5,rely=0.4,anchor=ui.CENTER)
#username_lable.pack()
username=ui.Entry(login,width=20,font=("Times",15),bd=2)
username.place(relx=0.5,rely=0.45,anchor=ui.CENTER)
#username.pack()
passwd_lable=ui.Label(login,text="Enter password",bg="white")
passwd_lable.place(relx=0.5,rely=0.5,anchor=ui.CENTER)
#passwd_lable.pack()
passwd=ui.Entry(login,width=20,font=("Times",15),bd=2,show="*")
passwd.place(relx=0.5,rely=0.55,anchor=ui.CENTER)
#passwd.pack()
login.mainloop()
